# Generated by Django 5.2 on 2025-07-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('loginId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('student_class', models.CharField(max_length=20, verbose_name='Class')),
                ('roll_no', models.CharField(max_length=20, verbose_name='Roll No.')),
                ('school_name', models.CharField(max_length=200, verbose_name='School Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone No.')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email Id')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('loginId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjects', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityStaff',
            fields=[
                ('loginId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Canteen Staff', max_length=100)),
            ],
        ),
    ]
